# Copyright 2019 Stanford University see LICENSE file
# CircleCI 2.0 configuration file

defaults: &defaults
  docker:
    - image: circleci/node:14.11.0
  working_directory: ~/sinopia_exporter

version: 2
jobs:
  dependencies:
    <<: *defaults
    steps:
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6'
      - checkout
      - restore_cache:
          key: dependency-cache-prod-{{ checksum "package.json" }}
      - run: npm install --only=production
      - save_cache:
          key: dependency-cache-prod-{{ checksum "package.json" }}
          paths:
            - node_modules
      - restore_cache:
          key: dependency-cache-ci-{{ checksum "package.json" }}
      - run: npm install # including CI/Test dependencies
      - save_cache:
          key: dependency-cache-ci-{{ checksum "package.json" }}
          paths:
            - node_modules
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-ci-{{ checksum "package.json" }}
      - run:
          name: Run linter (eslint)
          command: npm run eslint
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run jest unit tests
          command: |
            ./cc-test-reporter before-build
            npm run jest-ci
            ./cc-test-reporter after-build --exit-code $?
  register_latest_image:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache: # gives us back matching node_modules
          key: dependencies-prod-{{ checksum "package.json" }}
      - attach_workspace:
          at: .
      - run:
          name: Build & Register Images
          # NOTE: the env variables holding docker credentials are stored in the CircleCI dashboard
          command: |
            docker build -t ld4p/sinopia_exporter:latest --build-arg HONEYBADGER_API_KEY=$HONEYBADGER_API_KEY .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push ld4p/sinopia_exporter:latest
  register_stage_image:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache: # gives us back matching node_modules
          key: dependencies-prod-{{ checksum "package.json" }}
      - attach_workspace:
          at: .
      - run:
          name: Build & Register Images
          command: |
            docker build -t ld4p/sinopia_exporter:release-stage --build-arg HONEYBADGER_API_KEY=$HONEYBADGER_API_KEY .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push ld4p/sinopia_exporter:release-stage
  register_stage_and_prod_image:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache: # gives us back matching node_modules
          key: dependencies-prod-{{ checksum "package.json" }}
      - attach_workspace:
          at: .
      - run:
          name: Build & Register Images
          command: |
            docker build -t ld4p/sinopia_exporter:release-stage -t ld4p/sinopia_exporter:release-prod --build-arg HONEYBADGER_API_KEY=$HONEYBADGER_API_KEY .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push ld4p/sinopia_exporter:release-stage
            docker push ld4p/sinopia_exporter:release-prod
workflows:
  version: 2
  build:
    jobs:
      - dependencies:
          filters:
            branches:
              only:
                - /.*/
            tags:
              only:
                - /v.*/
      - build:
          requires:
            - dependencies
          filters:
            branches:
              only:
                - /.*/
            tags:
              only:
                - /v.*/
      - register_latest_image:
          requires:
            - build
          filters:
            branches:
              only:
                - main
            tags:
              ignore:
                - /v.*/
      - register_stage_image:
          requires:
            - build
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /v.[0-9\.]+-beta/
          context: ld4p
      - register_stage_and_prod_image:
          requires:
            - build
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /v.[0-9\.]+/
          context: ld4p
