# This is a basic workflow to help you get started with Actions

name: update_configs

# Controls when the action will run. 
on:
  # Triggers the workflow on push request events but only for the main branch
  push:
    tags:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "version"
  version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: main

      # Runs a set of commands using the runners shell
      - name: Use latest tag for version
        run: |
          export APP_VERSION=$(git describe --tags --always)
          sed -i -E "s/version\": \"(.*)\"/version\": \"${APP_VERSION:1}\"/" package.json;
          npm i
          git commit -am "Update to latest tagged version"
          git push origin main
